services:
  web:
    build: .
    image: profile-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    restart: always
    develop:
      watch:
        - path: ./src
          action: rebuild
          target: /usr/share/nginx/html
