services:
  node:
    image: profile-react:dev
    container_name: node
    build: .
    volumes:
      - ..:/workspaces:cached
      - vscode_server_volume:/root/.vscode-server
    command: sleep infinity

volumes:
  vscode_server_volume:
    driver: local
